format = """
[ 󰥓 ](bg:custom_black fg:custom_white)\
$os\
$username\
[](fg:custom_black bg:custom_white)\
$directory\
[](bg:custom_black fg:custom_white)\
$git_branch\
$git_status\
[](fg:custom_black bg:custom_white)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:custom_white bg:custom_black)\
$docker_context\
[](fg:custom_black bg:custom_white)\
$time\
[ ](fg:custom_white)\
"""

right_format = "[](bg:none fg:custom_white)$status[](bg:custom_white fg:custom_white)$cmd_duration"

palette = "glproj"

[palettes.glproj]
custom_red = "#FF0000"
custom_dark_yellow = "#d1d100"
custom_black = "#000000"
custom_white = "#FFFFFF"

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:custom_black fg:custom_white"
style_root = "bg:custom_black fg:custom_white" 
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:custom_white"
disabled = true # Disabled by default

[directory]
style = "bg:custom_white fg:custom_black fg:#000000"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = ""

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:custom_white fg:custom_black"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:custom_black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:custom_black"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:custom_white fg:custom_black"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:custom_white fg:custom_black"
format = '[ ](bg:custom_white fg:custom_black)[󰳭](bg:custom_white fg:custom_red)[ $time ]($style)'

[cmd_duration]
disabled = false
min_time = 0
style = "bg:custom_white fg:custom_black"
show_milliseconds = true
# show_notifications = true
# notification_timeout = 60000
format = "[󰔛 $duration]($style)"

[status]
disabled = false
symbol = "" # nf-fa-exclamation
success_symbol = ""
not_executable_symbol = " " # nf-fa-times_circle
not_found_symbol = " " # nf-fa-question_circle
sigint_symbol = " " # nf-fa-stop_circle
signal_symbol = "󰉁 " # nf-md-flash
style = "bg:custom_white fg:custom_black"
map_symbol = true
# recognize_signal_code = false
# pipestatus = true
pipestatus_separator = "|"
pipestatus_format = '\[$pipestatus\] => [$symbol$common_meaning$signal_name$maybe_int]($style)'
format = "[$symbol$status]($style)"
