[manager]
prepend_keymap = [
  { on = ["g", "v"], run = "cd ~/Vídeos"},
  { on = "y", run = ["plugin wl-clipboard", "yank"]},
  { on = "p", run = "plugin --sync smart-paste"},
  { on = [ "<C-n>" ], run = '''
    shell 'dragon-drop -x -i -T "$1"' --confirm
''' }
]
