[manager]
sort_by = "mtime"
sort_reverse = true
show_hidden = true

[opener]
edit = [	
  { run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open", orphan = true}
]

