init_widget = "List"
window_title = "ToDo tui"
layout = "[  Direction: Horizontal,  Size: 50%,  [    List: 80%, Preview: 20%,  ],  [    Direction: Vertical,    Done: 60%,    [      Contexts: 50%,      Projects: 50%,    ],  ],]"
paste_behavior = "Insert"
enable_mouse = true
use_done = false
pending_sort = "Priority"
done_sort = "None"
delete_final_date = true
set_final_date = "OnlyMissing"
todo_path = "$HOME/Anotações/todo.txt"
file_watcher = true
save_policy = "OnChange"
border_type = "Rounded"
list_shift = 4
pending_format = "[$subject](! priority)"
done_format = "[$subject](! priority)"
preview_format = """
Pending: $pending Done: $done
Subject: $subject
Priority: $priority
Create date: $create_date
Link: $link"""
wrap_preview = true
active_color = "Green"

[window_keybinds]
u = "Load"
"Shift+i" = "InsertMode"
"Shift+k" = "MoveUp"
"Shift+e" = "EditMode"
"Shift+l" = "MoveRight"
q = "Quit"
"Shift+s" = "Save"
"Shift+h" = "MoveLeft"
"Shift+j" = "MoveDown"
"/" = "SearchMode"

[list_refresh_rate]
secs = 5
nanos = 0

[autosave_duration]
secs = 900
nanos = 0

[tasks_keybind]
n = "NextSearch"
"Shift+n" = "PrevSearch"
"Shift+d" = "SwapDownItem"
Enter = "Select"
"Shift+u" = "SwapUpItem"
x = "RemoveItem"
d = "MoveItem"

[category_keybind]
Backspace = "Remove"
"Shift+n" = "PrevSearch"
Enter = "Select"
n = "NextSearch"

[list_keybind]
h = "CleanSearch"
j = "ListDown"
"Shift+g" = "ListLast"
g = "ListFirst"
k = "ListUp"

[list_active_color]
bg = "White"

[pending_active_color]

[done_active_color]

[category_active_color]

[projects_active_color]

[contexts_active_color]

[tags_active_color]

[priority_style.A]
fg = "#FF1111"
[priority_style.B]
fg = "#FF4444"
[priority_style.C]
fg = "#FF7777"
[priority_style.D]
fg = "#FF9999"
[priority_style.E]
fg = "#F0AAAA"

[projects_style]

[contexts_style]

[hashtags_style]

[category_style]

[category_select_style]
fg = "Green"

[category_remove_style]
fg = "Red"

[custom_category_style."+todo-tui"]
fg = "LightBlue"

[highlight]
bg = "Yellow"
