[package]
name = "screen_recorder"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dirs = "6.0.0"
duct = "0.13.7"
pico-args = "0.5.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
