#!/bin/fish
set pomodoro_status $(i3-gnome-pomodoro status --format=waybar --show-seconds)
if test -z $pomodoro_status
    echo '{"class": "paused", "text": "Pomodoro", "tooltip": "Right click to start."}'
else
    echo $pomodoro_status
end
